#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config top_padding 0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8 9 
bspc monitor DP2 -d 6 7 8 9

bspc config -m eDPI1 top_padding 22

bspc config remove_disabled_monitor true
bspc config remove_unpluged_monitor true
bspc config merge_overlapping_monitors true

bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a copyq floating=on
bspc rule -a mumble desktop=^5
bspc rule -a Friends floating=on

feh --randomize --bg-fill /media/Wallpaper/*

compton --config ~/.config/compton/compton.conf -b &

$HOME/.bin/panel/panel &
